spring.application.name=urlShortener

# database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update

# server configuration
server.port=${SERVER_PORT}